test:
	cd day3 && lein test

day1:
	cd day1 && bash day1.sh input.txt
day2 infile="input.txt":
	cd day2 && awk -f part1.awk < {{ infile }}
	cd day2 && awk -f part2.awk < {{ infile }}
day3 infile="input.txt":
	cd day3 && lein run {{ infile }}
day4 infile="input.txt":
	cd day4 && node . {{ infile }}

# Prepared solutions

fsharp:
	cd fsharp && dotnet run input.txt
haskell infile="input.txt":
	cd haskell && runhaskell main.hs {{ infile }}
julia infile="input.txt":
	cd julia && julia main.jl {{ infile }}
elixir infile="input.txt":
	cd elixir && elixir main.exs {{ infile }}
golang infile="input.txt":
	cd golang && go run main.go {{ infile }}
rust infile="input.txt":
	cd rust && cargo run -- {{ infile }}

