day1:
	cd day1 && bash day1.sh input.txt
day2 infile="input.txt":
	cd day2 && awk -f part1.awk < {{ infile }}
	cd day2 && awk -f part2.awk < {{ infile }}

# Prepared solutions

fsharp:
	cd fsharp && dotnet run input.txt
haskell infile="input.txt":
	cd haskell && runhaskell main.hs {{ infile }}
js infile="input.txt":
	cd javascript && node . {{ infile }}