default: fmt test check
alias r := run

export PYTHONPATH := "."

run day:
	cd src && python day{{ day }}/__init__.py

# Run unit tests
test:
	cd src && python -m pytest tests/

# Compile requirements
pipcompile:
	pip-compile -o requirements.txt requirements.in

# Format code
fmt:
	python -m black src
	python -m isort src

check:
	flake8 src
